name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0/10 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v3.0.11
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock', '**/pre-commit-config.yaml') }}
      - uses: actions/setup-python@v2
      - name: Setup git
        run: |-
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: python -m pip install --upgrade pip
      - run: pip install poetry
      - run: poetry install --no-root --remove-untracked
      - if: github.ref == 'refs/heads/main'
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: poetry run python updatehook.py
      - name: Commit and push if it changed
        if: github.ref == 'refs/heads/main'
        run: |-
          git add -A
          git commit -m "Scrape latest data" || exit 0
          git push
